break_time: '05'
dataset_path: exercises_dataset.json
medium_level_exercises_time: '18:55'
normal_count:
  base:
  - count: 12
    exercise: Squats
  medium:
  - count: 3
    exercise: Push Ups
  - count: 10
    exercise: Squats
reminder_time: '25'
time_check_rate: 25
warning_time: '55'
